= Séminaire 1

== La créativité est elle soluble dans l'intelligence artificelle

Lors du séminaire présenté par Thierry Dutoit le 8 octobre 2024, plusieurs aspects fascinants de l’évolution de l’IA ont été abordés, notamment la distinction entre #emph[street knowledge] et #emph[book knowledge]. Mr Dutoit a expliqué comment, à partir de 2009, l’IA a commencé à intégrer le "street knowledge", c’est-à-dire des systèmes capables d’apprendre par interaction avec le monde, comme les robots de Boston Robotics et les avancées en apprentissage par renforcement profond. À cela s'ajoute l’IA perceptive, notamment grâce aux réseaux neuronaux profonds et aux modèles de langage comme Word2Vec, développé par Thomas Mikolov chez Google en 2013.

L’un des points marquants était l’évolution vers des IA génératives et explicatives. Par exemple, les modèles de langage (LLMs) peuvent générer du contenu, tandis que l’IA explicative consiste à verbaliser les connaissances acquises par une machine, comme décrire un chat en détaillant ses caractéristiques physiques. Cette capacité à verbaliser ou à créer des œuvres soulève des questionnements sur le potentiel de l’IA à susciter des émotions ou à imiter la créativité humaine. Mr Dutoit a évoqué l’idée que la créativité pourrait être mesurée, un concept intrigant qui pousse à repenser notre rapport à la création.

Les ingénieurs d’aujourd’hui travaillent sur des systèmes d’IA capables d’assister non seulement la distribution et la production, mais aussi la création. Que ce soit dans la musique, avec des instruments numériques comme le Handsketch développé par Nicolas d’Alessandro, ou dans le domaine de la synthèse musicale et vocale, les possibilités semblent infinies. Dans le cinéma, des technologies comme le transfert de mouvement (utilisé dans le film "Avatar") ou l’animation automatique à partir de scripts montrent comment l’IA peut transformer des industries entières. L’IA générative, par exemple, permet aujourd'hui de créer des œuvres d’art à partir de texte avec des outils comme DALL-E ou MidJourney.

Le séminaire a également exploré des cas spécifiques d’IA créative, comme les réseaux antagonistes génératifs (GAN), qui ont donné naissance à des œuvres telles que "Le comte de Belamy", ou encore "Flow Machine", un projet ayant généré une chanson dans le style des Beatles. Les robots comme Shimon, un jazzman virtuel, ou encore les systèmes de suggestion d'aménagements intérieurs sont autant d'exemples de l'IA dans des domaines autrefois considérés comme exclusivement humains.

Cela amène naturellement la question de savoir si une machine peut véritablement être créative. Peut-on parler de #emph[créativité faible], où l'IA est un simple outil d’assistance, ou de #emph[créativité augmentée], dans laquelle l'humain guide le processus via des prompts et retouche le produit final ? Existe-t-il une forme de "créativité forte" propre aux machines ? Les robots peuvent-ils susciter la même admiration que les créateurs humains ?

L’une des réflexions centrales était celle de l’émotion. Mr Dutoit a mentionné le livre #emph[L’erreur de Descartes] de Damasio, soulignant que l’émotion est fondamentalement physique, enracinée dans notre corps. Or, les machines, n’ayant pas de corps, ne peuvent pas ressentir ou exprimer des émotions de manière authentique. Cependant, l’idée que les machines pourraient simuler des émotions, tout comme un avion simule le vol sans avoir d'ailes, reste ouverte. Nous, en tant qu’humains, avons une capacité extraordinaire à nous projeter dans le corps d’un autre, une qualité essentielle de l’art incarné. Peut-on faire la même chose avec des robots ?

Finalement, la conférence a posé une question fascinante : peut-on admirer un robot pour sa créativité ou son expressivité ? Il semble que l’effet de nouveauté, le "wow effect", pourrait s’estomper rapidement. Les œuvres générées par des machines, aussi impressionnantes soient-elles, ne sont pas inimitables, et leur reproduction en série pourrait diminuer l’admiration que nous leur portons. La curiosité pourrait nous amener à ajouter un robot dans notre liste d'amis sur Facebook, mais cela resterait un geste expérimental, une manière de tester les limites de l’interaction humain-machine.

Ce séminaire m'a beaucoup fait penser à une vidéo YouTube que j'ai vue récemment (https://www.youtube.com/watch?v=dOF9vc5tLJ4). Il s’agit de la critique de Mr Phi du livre #emph["L'Esprit artificiel : Une machine ne sera jamais philosophe"] de Raphaël Enthoven. Il est intéressant de noter que ce séminaire et le livre abordent la question des limites de l'intelligence artificielle d'un point de vue "créativité", mais sous des angles différents.

La critique de Mr Phi du livre d’Enthoven aborde la question de la créativité, mais plus spécifiquement celle de la capacité de philosopher. Enthoven affirme que l’IA ne peut pas philosopher, car elle est incapable de transformer une question en véritable problématique, c’est-à-dire d’engager cette réflexion profonde propre à l’humain, une forme de créativité en soi. Mr Phi conteste cette affirmation en reprochant à Enthoven de ne pas apporter de preuves tangibles à son argument. Ce débat sur l'incapacité de l'IA à philosopher rejoint la question soulevée par Mr Dutoit sur la capacité de l’IA à ressentir et à créer des œuvres véritablement émotionnelles.

En résumé, ces deux réflexions se rejoignent autour d'une même interrogation : jusqu'où l'IA peut-elle aller dans l'imitation des facultés humaines ? Qu'il s'agisse de la créativité artistique ou de la réflexion philosophique, il semble que les limites de l'IA soient encore floues et en constante évolution.

J'ai particulièrement apprécié les questions posées durant le séminaire, notamment une qui me tient à cœur et fait écho à la thèse de mémoire que j'ai terminée en juin 2024 sur la reproductibilité dans le génie logiciel (https://doi.org/10.5281/zenodo.13894231). Dans la conclusion de ce travail, j'avais souligné qu'une considération économique de la reproductibilité est que, lorsque quelque chose devient #emph[reproductible], il devient souvent moins onéreux à acquérir. Cette réflexion trouve un parallèle intéressant avec l'IA, notamment en ce qui concerne la création d'œuvres qui peuvent être reproduites à volonté. Si l'IA peut générer des œuvres d'art en masse, cela pourrait-il dévaluer la notion de créativité et d'originalité ? Ou bien, au contraire, cela pourrait-il démocratiser l'art et permettre à chacun de devenir créateur ?

En conclusion, l'IA est un puissant levier pour soutenir la créativité humaine, mais elle ne semble pas encore capable de la remplacer. La question de la véritable créativité, de l’émotion et de l’incarnation artistique restera au cœur des débats à venir, alors que les machines continuent de repousser les limites de ce que nous pensions être exclusivement humain.
