= Séminaire 2

== Intelligence Artificelle et Médecine

Lors du séminaire présenté par Giovanni Briganti, spécialiste en médecine computationnelle et neuropsychiatrie, plusieurs aspects de l’intelligence artificielle en médecine ont été abordés. Le point central était la manière dont l'IA peut transformer les soins de santé, tout en soulignant à la fois la complexité de son intégration dans le domaine médical et les implications éthiques qu'entraîne son déploiement dans ce milieu. Il a souligné que bien que les médecins puissent comprendre le fonctionnement des réseaux de neurones en raison de leurs similarités avec les neurones humains, l'IA présente des défis tant pour les techniciens que pour les cliniciens. L'IA ouvre de nouvelles perspectives, mais ne remplacera pas l’humain, particulièrement en ce qui concerne l’empathie et la compréhension de la souffrance.

Mr. Briganti a exploré les différentes applications de l'IA, notamment dans la surveillance des maladies chroniques, le diagnostic, la prédiction et la prévention. L'exemple de la radiologie montre à quel point l'IA peut être performante en identification et classification, rendant certaines tâches diagnostiques possibles sans l'intervention directe d’un médecin. Cependant, il a aussi souligné que l'IA a ses limites. Si elle est utile pour établir des corrélations et assister dans la prise de décision clinique, elle ne peut pas reproduire l'intelligence contre-factuelle humaine, c'est-à-dire la capacité à imaginer un monde sans la cause observée.

Une partie essentielle du discours a également porté sur l’impact sociétal de l’IA. En Belgique, avec ses nombreux chercheurs et startups dans le domaine de la santé digitale, l’adoption de l’IA est en pleine expansion. Toutefois, Mr. Briganti a insisté sur l'importance et la nécessité d’améliorer les processus de validation des systèmes d’IA, surtout avec l’arrivée de la l’IA act en 2025 et de sa future application obligatoire en 2027. Il a évoqué l'importance d'une collaboration étroite entre ingénieurs et médecins pour surmonter les défis techniques et garantir que les modèles soient à la fois valides et reproductibles.

L’éthique a été un autre sujet crucial. Mr. Briganti a souligné qu’il est dangereux de tomber dans le piège de l’automatisation complète en médecine, car l'humain, avec sa capacité à ressentir des émotions et à créer un lien empathique avec les patients, est irremplaçable. Le futur de l’IA en médecine nécessite un équilibre délicat entre automatisation, efficience et respect de la dimension humaine des soins de santé.

Pour conclure, Mr. Briganti a identifié trois grands axes de développement pour l’IA en médecine. Le premier concerne les modèles de langage, qui serviront d’interface principale pour interagir avec des IA multimodales. Le second porte sur les patients #emph[augmentés], dotés d'outils supplémentaires tels que S.A.R.A.H., une assistante numérique basée sur l’IA, fournissant des informations sur la santé. Enfin, l’IA pourra contribuer à la découverte de nouveaux antibiotiques. Il a souligné que, bien que l'IA possède un potentiel immense en médecine, nous devons repenser son développement et sa validation, et la Belgique pourrait encore progresser dans ce domaine.

J'ai trouvé l'intervention de Mr. Briganti particulièrement enrichissante. Elle a permis de mettre en lumière les enjeux et défis de l'intégration de l'IA en médecine, tout en soulignant les opportunités qu’elle offre pour améliorer les soins de santé. Ses propos rejoignent mes propres préoccupations concernant l'impact sociétal de l'IA et la nécessité de garantir que son déploiement se fasse de manière éthique, responsable, deterministe et open-source.
